# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: sqlite3
  database: db/sb_dev

test:
  adapter: sqlite3
  database: db/sb_test
  
production:
  adapter: sqlite3
  database: db/sb_prod

